services:
  mongodb:
    image: mongo:6-jammy
    container_name: cineos-mongodb
    ports:
      - "27017:27017"
    volumes:
      - cineos_mongo_data:/data/db
    restart: always

  redis:
    image: redis:7-alpine
    container_name: cineos-redis
    ports:
      - "6379:6379"
    volumes:
      - cineos_redis_data:/data
    command: redis-server --appendonly yes
    restart: always

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.3
    container_name: cineos-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    volumes:
      - cineos_es_data:/usr/share/elasticsearch/data
    restart: always

volumes:
  cineos_mongo_data:
  cineos_redis_data:
  cineos_es_data:
